---
title: "introduccionr_A01646343"
output: html_document
---

# 1
```{r}
dna_generator <- function(n) {
  bases <- c("A", "C", "T", "G")
  
  # Generar una secuencia aleatoria de longitud n
  sequence <- sample(bases, n, replace = TRUE)
  
  # Unir las bases para formar la secuencia de ADN
  return(paste(sequence, collapse = ""))
}

# Ejemplo de uso
dna_sequence <- dna_generator(15)
print(dna_sequence)

```

# 2
```{r}
dna_size <- function(sequence) {
  size <- nchar(sequence)
  return(size)
}

# Example usage
size <- dna_size(dna_sequence)
print(size)

```

# 3 
```{r}
base_percentage <- function(sequence) {
  # Initialize counters for each base
  A_count <- 0
  T_count <- 0
  C_count <- 0
  G_count <- 0
  
  # Loop through each base in the sequence and count them
  for (base in strsplit(sequence, NULL)[[1]]) {
    if (base == "A") {
      A_count <- A_count + 1
    } else if (base == "T") {
      T_count <- T_count + 1
    } else if (base == "C") {
      C_count <- C_count + 1
    } else if (base == "G") {
      G_count <- G_count + 1
    }
  }
  
  # Calculate the percentage of each base
  size <- nchar(sequence)
  A_percent <- (A_count / size) * 100
  T_percent <- (T_count / size) * 100
  C_percent <- (C_count / size) * 100
  G_percent <- (G_count / size) * 100
  
  cat("Percentage of A: ", A_percent, "%\n")
  cat("Percentage of T: ", T_percent, "%\n")
  cat("Percentage of C: ", C_percent, "%\n")
  cat("Percentage of G: ", G_percent, "%\n")
}
base_percentage(dna_sequence)

```
# 4
```{r}
# Función para transcribir ADN a ARN
transcribir_adn_a_arn <- function(cadena_adn) {
  # Tabla
  tabla <- c("G" = "C", "C" = "G", "T" = "A", "A" = "U")
  
  # Separar la cadena en caracteres
  bases_adn <- strsplit(cadena_adn, "")[[1]]
  
  # Inicializar cadena ARN vacía
  cadena_arn <- ""
  
  for (base in bases_adn) {
    cadena_arn <- paste0(cadena_arn, tabla[base])
  }
  
  return(cadena_arn)
}

cadena_arn <- transcribir_adn_a_arn(dna_sequence)
print(cadena_arn)
```
# 5
```{r}
# Función para traducir ARN a aminoácidos
traducir_arn_a_aminoacidos <- function(cadena_arn) {
# Mapa de codones a aminoácidos (simplificado)
  codones <- list(
  "UUU" = "Fenilalanina", "UUC" = "Fenilalanina",
  "UUA" = "Leucina",      "UUG" = "Leucina",
  "CUU" = "Leucina",      "CUC" = "Leucina",
  "CUA" = "Leucina",      "CUG" = "Leucina",
  "AUU" = "Isoleucina",   "AUC" = "Isoleucina",
  "AUA" = "Isoleucina",   "AUG" = "Metionina",  # Inicio
  "GUU" = "Valina",       "GUC" = "Valina",
  "GUA" = "Valina",       "GUG" = "Valina",

  "UCU" = "Serina",       "UCC" = "Serina",
  "UCA" = "Serina",       "UCG" = "Serina",
  "CCU" = "Prolina",      "CCC" = "Prolina",
  "CCA" = "Prolina",      "CCG" = "Prolina",
  "ACU" = "Treonina",     "ACC" = "Treonina",
  "ACA" = "Treonina",     "ACG" = "Treonina",
  "GCU" = "Alanina",      "GCC" = "Alanina",
  "GCA" = "Alanina",      "GCG" = "Alanina",

  "UAU" = "Tirosina",     "UAC" = "Tirosina",
  "UAA" = "STOP",         "UAG" = "STOP",
  "CAU" = "Histidina",    "CAC" = "Histidina",
  "CAA" = "Glutamina",    "CAG" = "Glutamina",
  "AAU" = "Asparagina",   "AAC" = "Asparagina",
  "AAA" = "Lisina",       "AAG" = "Lisina",
  "GAU" = "Ácido aspártico", "GAC" = "Ácido aspártico",
  "GAA" = "Ácido glutámico", "GAG" = "Ácido glutámico",

  "UGU" = "Cisteína",     "UGC" = "Cisteína",
  "UGA" = "STOP",         "UGG" = "Triptófano",
  "CGU" = "Arginina",     "CGC" = "Arginina",
  "CGA" = "Arginina",     "CGG" = "Arginina",
  "AGU" = "Serina",       "AGC" = "Serina",
  "AGA" = "Arginina",     "AGG" = "Arginina",
  "GGU" = "Glicina",      "GGC" = "Glicina",
  "GGA" = "Glicina",      "GGG" = "Glicina"
  )
# Dividimos la cadena ARN en codones
codones_arn <- strsplit(cadena_arn, "(?<=.{3})", perl = TRUE)[[1]]
# Traducimos cada codón a su aminoácido
proteina <- sapply(codones_arn, function(codon) codones[[codon]])
# Unimos los aminoácidos para formar la proteína
paste(proteina, collapse = "-")
}
# Ejemplo de traducción
aminoacidos <- traducir_arn_a_aminoacidos(cadena_arn)
print(aminoacidos)
```

# 6 
```{r}
# Función que construye la hebra inversa complementaria usando un ciclo for
obtener_hebra_inversa <- function(hebra_directa) {
  # Tabla de complementariedad
  complemento <- c("A" = "T", "T" = "A", "C" = "G", "G" = "C")
  
  hebra_inversa <- ""  # inicializamos cadena vacía
  
  for (i in 1:nchar(hebra_directa)) {
    base <- substr(hebra_directa, i, i)
    base_comp <- complemento[base]
    # Agregamos al inicio (para que quede invertido)
    hebra_inversa <- paste0(base_comp, hebra_inversa)
  }
  
  return(hebra_inversa)
}

# Ejemplo
hebra_directa <- "TGCGATAC"
hebra_inversa <- obtener_hebra_inversa(hebra_directa)

# Mostrar resultado
cat("Hebra directa:  5'-", hebra_directa, "-3'\n", sep = "")
cat("Hebra inversa:  3'-", hebra_inversa, "-5'\n", sep = "")
```

